<?php

use Drupal\Core\Session\AccountInterface;
use Drupal\user\UserInterface;

function hello_cron() {
    \Drupal::messenger()->addMessage(t('Hello cron'));
}

function hello_user_login(UserInterface $account) {
    \Drupal::messenger()->addMessage(t('Welcome dear %name!', [
        '%name' => $account->getAccountName(),
    ]));

    // ajout du log de login
    \Drupal::database()->insert('hello_user_statistics')->fields([
        'time' => \Drupal::time()->getCurrentTime(),
        'uid' => $account->id(),
        'action' => 1,
    ])->execute();
}

function hello_user_logout(AccountInterface $account) {
    // ajout du log de login
    \Drupal::database()->insert('hello_user_statistics')->fields([
        'time' => \Drupal::time()->getCurrentTime(),
        'uid' => $account->id(),
        'action' => 0,
    ])->execute();
}

function hello_views_data() {
    $data = [];
    $data['hello_user_statistics'] = [];

    $data['hello_user_statistics']['table'] = [];

    $data['hello_user_statistics']['table']['group'] = t('Hello Statistics table');

    $data['hello_user_statistics']['table']['provider'] = 'hello';

    $data['hello_user_statistics']['table']['base'] = [
      'field' => 'id',
      'title' => t('Hello Statistics table'),
      'help' => t('Hello Statistics help.'),
      'weight' => -10,
    ];

    $data['hello_user_statistics']['uid'] = [
      'title' => t('User id'),
      'field' => [
        'id' => 'numeric',
      ],
      'sort' => [
        'id' => 'standard',
      ],
      'filter' => [
        'id' => 'numeric',
      ],
      'relationship' => [
        'base' => 'users_field_data',
        'base field' => 'uid',
        'id' => 'standard',
        'label' => t('Hello UID -> User UID'),
      ],
    ];

    $data['hello_user_statistics']['action'] = [
      'title' => t('Action id'),
      'field' => [
        'id' => 'numeric',
      ],
      'sort' => [
        'id' => 'standard',
      ],
      'filter' => [
        'id' => 'numeric',
      ],
      'argument' => [
        'id' => 'numeric',
      ],
    ];

    $data['hello_user_statistics']['time'] = [
      'title' => t('Timestamp of user action'),
      'field' => [
        'id' => 'date',
      ],
      'sort' => [
        'id' => 'date',
      ],
      'filter' => [
        'id' => 'date',
      ],
    ];

    return $data;
}
